### ISSUE TITLE
Only one object gets rendered.

### ISSUE THREAD

**Issue by jsofra** [gered/clj-htmltopdf#1]
When converting html to pdf it seems only the first object is getting rendered.

**Comment by jsofra** [comment]
Looks like any tags after the object do not get rendered.
In the example from the README the final tag `[:p "Text after the object"]` does not get rendered.

```clojure
(->pdf
  [:div
   [:h2 "Object Drawing Test"]
   [:object {:id "the-object" :style "width: 400px; height: 300px;"}]
   [:p "Text after the object"]]
  "object.pdf"
  {:objects
   {:by-id
    {"the-object"
     (fn [object-element-attrs ^java.awt.Graphics2D g]
       (.setColor g java.awt.Color/RED)
       (.drawRect g 50 50 200 200)
       (.setColor g java.awt.Color/BLUE)
       (.drawRect g 75 75 300 200))}}})
```

**Comment by gered** [comment]
Hmm, interesting, I could swear that was working just fine previously (I clearly recall testing a document with two object tags and text in-between). I'll take a look!

**Comment by gered** [comment]
Your example actually works perfectly for me.

![image](https://user-images.githubusercontent.com/633985/41774060-2d1d68f6-75ec-11e8-9357-03535a7b761a.png)

Could you double check?
