### ISSUE TITLE
Error getting started: 'clj-htmltopdf.options' not found

### ISSUE THREAD

**Issue by emgrasmeder** [gered/clj-htmltopdf#2]
Hi there, 
I'm getting the error 
```
CompilerException java.lang.Exception: namespace 'clj-htmltopdf.options' not found, compiling:(clj_htmltopdf/core.clj:1:1)
```
after adding `[clj-htmltopdf "0.1-alpha5"]` to my project.clj and trying to do `(use 'clj-htmltopdf.core)`

Any ideas why this is failing?
Thanks

**Comment by gered** [comment]
Sorry, it seems I made a little mistake in the latest release. I apologize for the inconvenience. I'll try to get a fix out soon.

So that you're not stuck waiting for me, you can just use the previous release  
`[clj-htmltopdf "0.1-alpha4"]`.

**Comment by gered** [comment]
I've just pushed out `[clj-htmltopdf "0.1-alpha6"]` which fixes that compile error. Let me know if you continue running into any trouble.
